<?php

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_balloonpanel_ckeditor_plugin() {
  return array(
    'ckeditor_balloonpanel' => array(
      'name' => 'ckeditor_balloonpanel',
      'desc' => t('CKEditor Balloon Panel'),
      'path' => '',
    ),
  );
}

/**
 * Defines the "balloonpanel" plugin.
 *
 * @CKEditorPlugin(
 *   id = "balloonpanel",
 *   label = @Translation("Balloon Panel Plugin"),
 * )
 */
class BalloonPanelPlugin extends CKEditorPluginBase {

  /**
   * {@inheritdoc}
   */
  public function getFile() {
    return base_path() . 'libraries/balloonpanel/plugin.js';
  }

  /**
   * {@inheritdoc}
   */
  public function getConfig(Editor $editor) {
    return [];
  }

  /**
   * {@inheritdoc}
   */
  public function getButtons() {
    return [];
  }

}
