<?php

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_balloonpanel_ckeditor_plugin() {
  return array(
    'balloonpanel' => array(
      'name' => 'balloonpanel',
      'desc' => t('CKEditor Balloon Panel'),
      'path' => libraries_get_path('balloonpanel', TRUE) . '/',
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function ckeditor_balloonpanel_libraries_info() {
  return array(
    'balloonpanel' => array(
      'name' => 'CKEditor Balloon Panel',
      'vendor url' => 'http://ckeditor.com/addon/balloonpanel',
      'download url' => 'http://ckeditor.com/addon/balloonpanel',
    ),
  );
}
